### ISSUE TITLE
번개 글 참석자 관련 데이터 논의

### ISSUE THREAD

**Issue by Windowmincastle** [NoExit13/NoExit#43]
번개 글에 참석자들이 참가 신청을 누른 후
추후 참가자들을 채팅방에 모으려면 참가 신청 버튼을 누른
회원들의 정보를 저장해야할 것 같습니다. DB에 저장을 해야할지
해당 게시글에 내부적으로 참가자들의 정보를 달고 다녀야할지 고민 입니다.

**Comment by 34suuuuu** [comment]
참가버튼을 누를 때 레디스에 추가할 수 있도록 구현하는 방법은 어떨까요? 
강사님께 여쭤보니 애초에 모집하는 인원이 적은편이라 동시성 이슈까지는 다루지 않아도 될 것 같다고 하셨어요! 
해당 게시글 아이디? 정도랑 버튼을 누른 회원 정보를 토큰에서 가져와서 저장하는 식으로 해봐도 좋을 것 같아요

**Comment by Windowmincastle** [comment]
> 참가버튼을 누를 때 레디스에 추가할 수 있도록 구현하는 방법은 어떨까요? 강사님께 여쭤보니 애초에 모집하는 인원이 적은편이라 동시성 이슈까지는 다루지 않아도 될 것 같다고 하셨어요! 해당 게시글 아이디? 정도랑 버튼을 누른 회원 정보를 토큰에서 가져와서 저장하는 식으로 해봐도 좋을 것 같아요

**Comment by 34suuuuu** [comment]
저는 오랫동안 남겨둘 데이터는 아니라고 생각해서 redis 생각했는데 rdb도 좋습니다! 어차피 중복으로 참여할 수 없으니 따로 중복처리 안해줘도되고 좋네요
