### ISSUE TITLE
키 값을 참조하는 컬럼의 생성 -> 삭제 -> 생성 할때의 오류

### ISSUE THREAD

**Issue by leem5514** [NoExit13/NoExit#71]
More than one row with the given identifier was found: 11, for class: com.E1i3.NoExit.domain.review.domain.Review; nested exception is org.hibernate

reservation에서의 reservation_id 을 가지고  -> review 을 생성을 한다
이때 review 에서 delYN의 상태를 Y 으로 바꾸는 경우 삭제가 되었다 가정한다.
후 다시 사용하였던 RESERVATION_ID 을 통한 리뷰 재 생성시 위의 오류가 발생하면서 리스트 조회 전부분이 불가능 처리된다.

위 에러는 말 그대로 RESERVATION 과 REVIEW 는 ONETOONE 관계인데 왜 식별자를 2번을 사용하는 가에 대한 에러이다

이를 해결하기 위해 서치한 방법으로
DELYN인 N 인 데이터만 조회하라는 방법
이 방법은 이미 전반적으로 사용중인 방법이라 해결책이 아니다.

**Comment by 34suuuuu** [comment]
아주 삭제하는게 방법일거 같은데 저희는 모두 delyn으로 통일하기로 했으니깐 해당 reservation 아이디가 존재하는지 확인해서 존재하지 않는다면 추가, 존재한다면 update가 방법인 것 같아요
